name: AVITAI
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.74572
title: AVITAI
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cccacf'
    - '#302e31'
    - '#cb5e37'
    - '#a81616'
  brandStrength: 0.25
  lightness: 0.81529505783692
  saturation: 0.8125
  rhythmicContrast: 0.4697878865990788
purpose: []
