name: AVITAI
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74572
title: AVITAI
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#ce1c00'
    - '#38b471'
    - '#f38711'
  brandStrength: 0.6875
  lightness: 0.81529505783692
  saturation: 0.7404198187869042
  rhythmicContrast: 0.4697878865990788
purpose: []
